version: '3'

services:
    nginx:
        image: nginx:1.13
        ports:
            - '8000:80'
        links:
            -  wordpress
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
            - ./logs/:/var/log/nginx/
            - wordpress_data:/var/www/html
            - ./theme:/var/www/html/wp-content/themes/the_theme
            - ./plugins:/var/www/html/wp-content/plugins
            - ./uploads:/var/www/html/wp-content/uploads
        restart: always
    db:
        image: mariadb:10.2
        ports:
            #- '9002:3306'
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=somewordpress
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress

        restart: always

    wordpress:
        links:
            - db
            - mailhog
        image: jnollette/wordpress_development_cli:latest
        volumes:
            - wordpress_data:/var/www/html
            - ./theme:/var/www/html/wp-content/themes/the_theme
            - ./plugins:/var/www/html/wp-content/plugins
            - ./uploads:/var/www/html/wp-content/uploads
        restart: always
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_NAME=wordpress
            - WORDPRESS_DEBUG=true
    mailhog:
        image: mailhog/mailhog
        ports:
            #- 1025:1025
            - 8100:8025
            
volumes:
     wordpress_data:
